// Sahih al-Bukhari selections. The text is generated by scripts/fetch-hadith.mjs from
// fawazahmed0/hadith-api (Muhsin Khan translation) — never edit hadith.json by hand.
import data from '@/data/hadith.json';

export type Hadith = { number: number; theme: string; narrator: string; text: string };

export const HADITHS = data as Hadith[];

export const sunnahUrl = (n: number) => `https://sunnah.com/bukhari:${n}`;

/** The same hadith all day for everyone at the same place, changing at local midnight. */
export function hadithOfDay(day: Date) {
  const start = new Date(day.getFullYear(), 0, 0);
  const dayOfYear = Math.round((day.getTime() - start.getTime()) / 86_400_000);
  return HADITHS[(day.getFullYear() * 366 + dayOfYear) % HADITHS.length];
}
